# Generated by Django 3.2.12 on 2022-03-15 11:14

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_user',
            field=models.ForeignKey(default=django.contrib.auth.models.User, help_text='申请人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_user', to=settings.AUTH_USER_MODEL, verbose_name='申请人'),
        ),
        migrations.AlterField(
            model_name='application',
            name='divide_use',
            field=models.ForeignKey(default=django.contrib.auth.models.User, help_text='分发人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='divide_use', to=settings.AUTH_USER_MODEL, verbose_name='分发人'),
        ),
    ]
