# Generated by Django 3.2.12 on 2022-03-15 11:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0002_auto_20220315_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_date',
            field=models.DateField(default=datetime.datetime.now, help_text='申请日期', verbose_name='申请日期'),
        ),
        migrations.AlterField(
            model_name='application',
            name='application_mark',
            field=models.CharField(blank=True, help_text='申请备注', max_length=255, null=True, verbose_name='申请备注'),
        ),
        migrations.AlterField(
            model_name='application',
            name='divide_mark',
            field=models.CharField(blank=True, help_text='分发备注', max_length=255, null=True, verbose_name='分发备注'),
        ),
        migrations.AlterField(
            model_name='application',
            name='divide_use',
            field=models.ForeignKey(help_text='分发人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='divide_use', to=settings.AUTH_USER_MODEL, verbose_name='分发人'),
        ),
        migrations.AlterField(
            model_name='application',
            name='receive_date',
            field=models.DateField(default=datetime.datetime.now, help_text='领用日期', verbose_name='领用日期'),
        ),
    ]
