# Generated by Django 3.2.12 on 2022-03-15 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0003_auto_20220315_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_user',
            field=models.ForeignKey(help_text='申请人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_user', to=settings.AUTH_USER_MODEL, verbose_name='申请人'),
        ),
        migrations.AlterField(
            model_name='application',
            name='receive_date',
            field=models.DateField(help_text='领用日期', null=True, verbose_name='领用日期'),
        ),
    ]
