# Generated by Django 3.2.12 on 2022-03-15 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20220315_1148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'permissions': [('csv', '导出csv格式数据'), ('excel', '导出excel格式数据')], 'verbose_name': '物品详情', 'verbose_name_plural': '物品详情'},
        ),
    ]
