# Generated by Django 3.2.12 on 2022-03-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_alter_application_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_purchase',
            field=models.BooleanField(blank=True, default=False, help_text='是否购买', null=True, verbose_name='是否购买'),
        ),
        migrations.AddField(
            model_name='application',
            name='is_reach',
            field=models.BooleanField(blank=True, default=False, help_text='是否收到', null=True, verbose_name='是否收到'),
        ),
        migrations.AddField(
            model_name='application',
            name='is_receive',
            field=models.BooleanField(blank=True, default=False, help_text='是否领取', null=True, verbose_name='是否领取'),
        ),
    ]
