# Generated by Django 3.2.12 on 2022-03-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_auto_20220317_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='purchase_date',
            field=models.DateField(blank=True, help_text='采购日期', null=True, verbose_name='采购日期'),
        ),
        migrations.AlterField(
            model_name='application',
            name='reach_date',
            field=models.DateField(blank=True, help_text='到货日期', null=True, verbose_name='到货日期'),
        ),
    ]
