# Generated by Django 3.2.12 on 2022-03-21 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_auto_20220317_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'permissions': [('csv', '导出csv格式数据'), ('json', '导出json格式数据'), ('goods_reach_notify', '物品达到')], 'verbose_name': '物品详情', 'verbose_name_plural': '物品详情'},
        ),
    ]
